<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>2ec91853-9aaf-4049-9aeb-7e4ebb025cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cursor-pointer.btn.btn-neutral.relative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aae1e49a-c6ad-44c7-bf9c-33e7b3682aff']/div[2]/div/div/div/div[2]/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b32693f1-92b0-4268-81c6-a3ea8d55cc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer btn btn-neutral relative</value>
      <webElementGuid>f8e50ec1-47f9-463f-b51c-120f0d742110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>4aa5a110-e00b-405d-915f-fc0385b7b301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aae1e49a-c6ad-44c7-bf9c-33e7b3682aff&quot;)/div[@class=&quot;relative flex flex-col w-11/12 user-turn&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/div[@class=&quot;flex min-h-[20px] max-w-full flex-grow flex-col gap-0&quot;]/div[@class=&quot;text-message flex min-h-[20px] flex-col items-start gap-3 overflow-visible [.text-message+&amp;]:mt-5&quot;]/div[@class=&quot;mt-2 flex w-full justify-center text-center&quot;]/button[@class=&quot;cursor-pointer btn btn-neutral relative&quot;]</value>
      <webElementGuid>21f6c459-ea04-4d14-ac8a-53b5c8dcbe6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aae1e49a-c6ad-44c7-bf9c-33e7b3682aff']/div[2]/div/div/div/div[2]/button[3]</value>
      <webElementGuid>f674cee1-b7ff-4c6a-8280-2fbb4ccf9f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[1]</value>
      <webElementGuid>0ba54733-a67d-46e3-8a4c-fa12d3ac0ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Submit'])[1]/following::button[2]</value>
      <webElementGuid>f0a15652-a37c-4c3b-af34-b4b0ff27c48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Response 2:'])[1]/preceding::button[5]</value>
      <webElementGuid>fff9a93b-0467-454a-bb1a-e3d26cef725d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>663353ea-f0c1-43d8-a3d8-0e70055cfe9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/button[3]</value>
      <webElementGuid>428365fd-e5f6-4825-90a5-f98f16a39293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>e41e48d8-a922-4c0a-b1bf-e055fea068eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
