analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3494313,"name"\:"OrangeHRM Trial \#3494313","teamId"\:3488153,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3506164,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3488153,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
