<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_sidebar</name>
   <tag></tag>
   <elementGuidId>0848c7f3-a983-4a4e-b302-37b91d2b3099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e58c5b71-12da-4111-8791-b37e64d6a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1782355632792</value>
      <webElementGuid>fe047aa6-f651-439c-8e6c-1077bb9fdc02</webElementGuid>
   </webElementProperties>
</WebElementEntity>
