<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sellect_llama-3-1-8b-v1-rngd</name>
   <tag></tag>
   <elementGuidId>38835342-8bdc-4ca1-9f16-6fbaf67963ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.w-full.min-w-0.items-center.gap-2.px-1.py-1 > span.truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r3o:']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;llama-3-1-8b-v1-rngd&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd0a0b99-e5a2-447c-9389-4ea2bad1363f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate</value>
      <webElementGuid>fc349e1c-8b8c-475a-a86b-9e766af52f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>llama-3-1-8b-v1-rngd</value>
      <webElementGuid>60d33413-f911-433f-8498-0b0f606527d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r3o:&quot;)/div[@class=&quot;flex w-full min-w-0 items-center gap-2 px-1 py-1&quot;]/span[@class=&quot;truncate&quot;]</value>
      <webElementGuid>1cf51acd-ef37-4561-932c-32bdbf1214cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r3o:']/div/span</value>
      <webElementGuid>d7b37ec9-0c88-4342-b1bd-cf3822005035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search sys_test_npu models...'])[1]/following::span[1]</value>
      <webElementGuid>f248f147-a380-49ac-ac67-54a76d96015f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test-1-dudaji'])[1]/following::span[8]</value>
      <webElementGuid>acbfd81a-0c72-4178-8e20-85385109b3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='llama-3-1-8b-v1-rngd']/parent::*</value>
      <webElementGuid>f56d209c-4052-4403-b8e2-949a1ebd956f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/span</value>
      <webElementGuid>df3d3bd3-624d-4c61-a0e5-659a9d360f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'llama-3-1-8b-v1-rngd' or . = 'llama-3-1-8b-v1-rngd')]</value>
      <webElementGuid>613d5f4d-f2b2-4afd-8906-989808921c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
