<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Agents</name>
   <tag></tag>
   <elementGuidId>950c48ce-b7fa-4727-8364-4fc7b6283274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flex-grow.truncate.text-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=':rj:']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select a model&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9423d2a6-3b72-4ff4-af91-09b843ee3960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow truncate text-left</value>
      <webElementGuid>0515bafe-97d1-4291-b794-82cc8f04f7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Agents</value>
      <webElementGuid>18913e5d-b2c4-4ac4-bd4b-06156a60a6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rj:&quot;)/span[@class=&quot;flex-grow truncate text-left&quot;]</value>
      <webElementGuid>ea18450c-b237-461a-96b1-fbbc5adf4b09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id=':rj:']/span</value>
      <webElementGuid>db35f2c6-fc09-4f24-b1f2-015635130952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initial Greeting'])[1]/following::span[1]</value>
      <webElementGuid>e5ae1703-e072-4a0f-a53a-e0a98ffcda1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logo Description'])[1]/following::span[1]</value>
      <webElementGuid>17a27dbb-9722-4505-b693-80c943abd00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Nufi Chat.'])[1]/preceding::span[1]</value>
      <webElementGuid>b6630f5c-fe9c-4634-9b84-81041adcb3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='W'])[1]/preceding::span[2]</value>
      <webElementGuid>91512ee0-f4ef-4c5f-9b8a-40dcdbcc2365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Agents']/parent::*</value>
      <webElementGuid>6447454b-a784-4cc8-8617-9021fc21100d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div/div/div/button/span</value>
      <webElementGuid>5da751b1-082c-42d2-a217-43ca27cda80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My Agents' or . = 'My Agents')]</value>
      <webElementGuid>c37d872c-36da-43cb-854f-0d1b49c17de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
