<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_Select a fork</name>
   <tag></tag>
   <elementGuidId>a3277903-9bf0-48ea-981d-317779f171b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r1o:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc68c6c0-5e19-4e7f-8800-1c682011eb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1o:</value>
      <webElementGuid>163b2462-08fc-49e2-9f28-77f477fae745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a57aeb32-a31b-4049-810b-72781a0e3abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>57b921b1-8c4f-4841-ab02-1f161cfe07f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c032721d-4319-4c0f-9122-aef2bc119823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-animate open flex w-60 flex-col gap-3 overflow-hidden rounded-2xl border border-border-medium bg-surface-secondary p-2 px-4 shadow-lg</value>
      <webElementGuid>4c91a041-c795-492d-a8b1-e23374edc1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0d58948-6600-40f7-86b2-4428726d0345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a fork optionView detailed explanation of all fork options and their behaviorsVisible messages onlyView additional information and details about the &quot;Visible messages only&quot; fork optionInclude related branchesView additional information and details about the &quot;Include related branches&quot; fork optionInclude all to/from hereView additional information and details about the &quot;Include all to/from here&quot; fork optionStart fork hereIf checked, forking will commence from this message to the latest message in the conversation, according to the behavior selected above.RememberCheck this to remember the options you select for future usage, making it quicker to fork conversations as preferred.</value>
      <webElementGuid>9ef81919-dbdb-4014-81de-a5191b587a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1o:&quot;)</value>
      <webElementGuid>a4e9e907-1fe2-48e2-8ebe-59be0ff39720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r1o:']</value>
      <webElementGuid>c0510381-1778-426d-8efe-601733cc8f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal/:r1o:']/div/div</value>
      <webElementGuid>81e5e019-017c-4565-98d3-ea1b09416a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[3]</value>
      <webElementGuid>c01b087d-e473-4f62-935b-46068cb30ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[5]</value>
      <webElementGuid>40554204-125e-44fb-ae49-6c0cc0f11fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>638aa542-819f-4da7-bbab-c5d7d4b36aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r1o:' and (text() = 'Select a fork optionView detailed explanation of all fork options and their behaviorsVisible messages onlyView additional information and details about the &quot;Visible messages only&quot; fork optionInclude related branchesView additional information and details about the &quot;Include related branches&quot; fork optionInclude all to/from hereView additional information and details about the &quot;Include all to/from here&quot; fork optionStart fork hereIf checked, forking will commence from this message to the latest message in the conversation, according to the behavior selected above.RememberCheck this to remember the options you select for future usage, making it quicker to fork conversations as preferred.' or . = 'Select a fork optionView detailed explanation of all fork options and their behaviorsVisible messages onlyView additional information and details about the &quot;Visible messages only&quot; fork optionInclude related branchesView additional information and details about the &quot;Include related branches&quot; fork optionInclude all to/from hereView additional information and details about the &quot;Include all to/from here&quot; fork optionStart fork hereIf checked, forking will commence from this message to the latest message in the conversation, according to the behavior selected above.RememberCheck this to remember the options you select for future usage, making it quicker to fork conversations as preferred.')]</value>
      <webElementGuid>661defce-d9eb-42c7-9b1a-4d021b2c943e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
