<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>remember-checkbox</name>
   <tag></tag>
   <elementGuidId>ace0c317-ed33-4ae5-8c68-d674ed22ebf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember-checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;RememberCheck this to remember the options you select for future usage, making i&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83690c2b-ce03-40da-8df5-3540f6d901c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between</value>
      <webElementGuid>45c6df4e-e521-440f-a04c-edad7401e32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RememberCheck this to remember the options you select for future usage, making it quicker to fork conversations as preferred.</value>
      <webElementGuid>84bcdecc-ab05-4880-8f88-ccc7a7ea029b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2c:&quot;)/div[@class=&quot;flex items-center justify-between&quot;]</value>
      <webElementGuid>16ca7bae-da7f-43a1-8458-bb33456658e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r2c:']/div[4]</value>
      <webElementGuid>1523f9b7-e5fb-4dad-861b-2333ca0b8174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start fork here'])[1]/following::div[1]</value>
      <webElementGuid>351863a1-a6d7-4920-9894-59e0ef3d65c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include all to/from here'])[1]/following::div[3]</value>
      <webElementGuid>396c4021-5a4e-4ba7-ae43-5761521f0b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]</value>
      <webElementGuid>39ecb37f-9f51-467f-b0da-aedbbe45175b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RememberCheck this to remember the options you select for future usage, making it quicker to fork conversations as preferred.' or . = 'RememberCheck this to remember the options you select for future usage, making it quicker to fork conversations as preferred.')]</value>
      <webElementGuid>7f6ab2ee-cd47-433a-b6f9-4cd84af216fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
