<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sellect_Qwen2.5-0.5B</name>
   <tag></tag>
   <elementGuidId>e03c5317-ce3f-41e5-b143-83bb9b4d473e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.w-full.min-w-0.items-center.gap-2.px-1.py-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r1m:']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Qwen2.5-0.5B Pin&quot;i] >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c031472-0a63-4605-ad1f-dcb25155b6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full min-w-0 items-center gap-2 px-1 py-1</value>
      <webElementGuid>26dd24e8-d6c3-4e27-acb2-1cbf5b99ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qwen2.5-0.5B</value>
      <webElementGuid>1030e566-7660-4c9f-8a03-df9998621e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1m:&quot;)/div[@class=&quot;flex w-full min-w-0 items-center gap-2 px-1 py-1&quot;]</value>
      <webElementGuid>94d8f611-d501-40d5-9ede-172e1db887ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r1m:']/div</value>
      <webElementGuid>1c00b52b-89d2-4d2f-bfe7-222d3a80b9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Nufi models...'])[1]/following::div[3]</value>
      <webElementGuid>4ac8f077-efe4-46b2-b7e6-00dcc881ebf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gemini'])[1]/following::div[9]</value>
      <webElementGuid>d8033147-ce2a-4d8e-83e5-6028628d0bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>59156b85-1538-43b1-b714-ef5d025e7f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Qwen2.5-0.5B' or . = 'Qwen2.5-0.5B')]</value>
      <webElementGuid>44101893-add0-4dca-a7d8-911a50e7f4d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
