<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom Name</name>
   <tag></tag>
   <elementGuidId>2d34e24e-78b7-4b95-933e-f9903981d5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modelLabel-dynamic-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='modelLabel-dynamic-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Set a custom name for the AI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e75dfea4-7bcd-496c-9ce3-68d8fab5a4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 flex h-9 max-h-9 w-full resize-none rounded-lg border border-border-light bg-surface-secondary px-3 py-2</value>
      <webElementGuid>8464b332-91dc-446e-9e6d-4ab3b731e4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modelLabel-dynamic-input</value>
      <webElementGuid>71b3b10f-0950-4b94-b5a8-889c04814dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Set a custom name for the AI</value>
      <webElementGuid>b3386391-4878-458c-a407-7c53baa05671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modelLabel-dynamic-input&quot;)</value>
      <webElementGuid>5899d6ba-ceb0-41f8-8d96-ce31b54f6cb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='modelLabel-dynamic-input']</value>
      <webElementGuid>04cc8894-3bdb-4894-a819-475c246c853d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/aside/div/nav/div/div/div/div/a/input</value>
      <webElementGuid>88a5e688-c073-4bcb-9339-4cd0a67dfe71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9509b7ee-084f-44e5-8fb2-7124ca41d0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'modelLabel-dynamic-input' and @placeholder = 'Set a custom name for the AI']</value>
      <webElementGuid>c29bf346-c76b-4daf-8f52-a2b248c85d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
