<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider_top-p_thumb</name>
   <tag></tag>
   <elementGuidId>629d3b00-242e-4b22-96d3-fa35967d2716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='top_p-dynamic-setting-slider']/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Top P&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>44b68fa9-02b5-4571-ad12-c837f8ad4900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>924c67e3-a59e-4d53-848c-67691ebad591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Top P</value>
      <webElementGuid>950ff5d2-a73a-42c6-89b7-e66e83e36f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b7cdfeb-592d-43d9-b6c5-62f790c8b8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e9787284-85bf-4d92-81d4-bd68c8045874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>28a20b4d-16de-4967-b472-7d7fef2d8466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>horizontal</value>
      <webElementGuid>557da2b9-f577-4f99-803a-bb7dcabda1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c6919d4-66d2-4e80-aac4-05c93b146265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50</value>
      <webElementGuid>1a07d018-0662-4ca9-8056-1ffadc4518ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0.18</value>
      <webElementGuid>2a23d8ef-d32e-4c82-b6f1-639c55390492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top_p-dynamic-setting-slider&quot;)/span[2]/span[@class=&quot;block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50&quot;]</value>
      <webElementGuid>53f04fb7-3ff6-47ce-9c21-9b647ac2ad67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='top_p-dynamic-setting-slider']/span[2]/span</value>
      <webElementGuid>a439b6f8-cd61-44e9-b6e3-6898fd7cc586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/span/span[2]/span</value>
      <webElementGuid>8d905906-08b8-4dd9-a2da-706f92964b8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
