<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Usage</name>
   <tag></tag>
   <elementGuidId>9a7a45c0-c18f-4e50-8e3d-3af1f3b604e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/nav/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Usage&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c71ae27-c150-44ee-86e5-cee39e77f8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/usage</value>
      <webElementGuid>dc75781b-cb89-48b5-acc7-23502f8a8afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-muted-foreground transition-colors hover:text-foreground</value>
      <webElementGuid>d3a6500c-93e4-4134-9d02-33bd9364d901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Usage</value>
      <webElementGuid>5daaa612-753f-4919-952f-70bf4a331451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-dvh bg-background text-foreground&quot;]/header[@class=&quot;border-b&quot;]/div[@class=&quot;mx-auto flex h-14 max-w-5xl items-center gap-4 px-4 sm:gap-6 sm:px-6&quot;]/nav[@class=&quot;flex flex-1 items-center gap-3 text-sm sm:gap-4&quot;]/a[@class=&quot;text-muted-foreground transition-colors hover:text-foreground&quot;]</value>
      <webElementGuid>7f9badab-0af1-40f1-8120-147317378c5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/nav/a[2]</value>
      <webElementGuid>c2cc5942-1f55-4a5e-8f52-57e27fa70aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Usage')]</value>
      <webElementGuid>0b338d17-6d84-44b8-9fb1-472bb4da5109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::a[1]</value>
      <webElementGuid>ec4cb401-0183-4d3a-99aa-51c4240fca11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NUFI Console'])[2]/following::a[2]</value>
      <webElementGuid>6005fa48-3c8a-49f0-8ca0-632991ac2635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API keys'])[1]/preceding::a[1]</value>
      <webElementGuid>9b3fa224-5a7d-43b6-abfa-c3cf1c9c932b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi 👋'])[1]/preceding::a[2]</value>
      <webElementGuid>a43d016b-b1c3-4a6e-9486-02258b87e382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Usage']/parent::*</value>
      <webElementGuid>2c54763f-065f-4f9e-948f-400603449981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/usage')]</value>
      <webElementGuid>ef0995b5-5c54-4aa4-b714-3334e1548224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>bb4536f8-a9de-44dc-b7ac-ef0c2714b2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/usage' and (text() = 'Usage' or . = 'Usage')]</value>
      <webElementGuid>8d02bbac-de55-4364-bb5b-b693a7b4e734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
