<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Include endpoint options</name>
   <tag></tag>
   <elementGuidId>e97d7229-2c59-4f85-91d9-6443977d5b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r59:']/div[2]/div/div[2]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Include endpoint options&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f982d446-2524-4988-99a5-63dbf0d73884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>includeOptions</value>
      <webElementGuid>43a1daae-7c44-4382-b4bc-959c9fc683b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full break-all peer-disabled:cursor-not-allowed peer-disabled:opacity-70 dark:text-gray-200 text-left text-sm font-medium</value>
      <webElementGuid>b5194986-189c-4e8e-b4f2-046a91ec3d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Include endpoint options</value>
      <webElementGuid>e97fb2cc-4e7a-4d2a-8a5f-fc989555a2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r59:&quot;)/div[@class=&quot;px-0 py-2&quot;]/div[@class=&quot;flex w-full flex-col items-center gap-6&quot;]/div[@class=&quot;grid w-full gap-6 sm:grid-cols-2&quot;]/div[@class=&quot;col-span-1 flex flex-col items-start justify-start gap-2&quot;]/div[@class=&quot;grid w-full items-center gap-2&quot;]/label[@class=&quot;block w-full break-all peer-disabled:cursor-not-allowed peer-disabled:opacity-70 dark:text-gray-200 text-left text-sm font-medium&quot;]</value>
      <webElementGuid>db6f049e-da9b-4248-9dca-c3bd9d4a0e62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r59:']/div[2]/div/div[2]/div/div/label</value>
      <webElementGuid>58befae3-0126-4b6d-bd4c-cc4e57c409c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='csv (.csv)'])[1]/following::label[1]</value>
      <webElementGuid>ab54a310-70b9-4991-a2c3-4fc4afed2129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='json (.json)'])[1]/following::label[1]</value>
      <webElementGuid>7a743598-275c-4cad-a0d4-6b06333af396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Supported'])[1]/preceding::label[1]</value>
      <webElementGuid>7f02b694-586d-4d83-ac28-61fb60c8fee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export all message branches'])[1]/preceding::label[2]</value>
      <webElementGuid>10f9cb62-ca99-4a17-a3a1-310c3897dd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Include endpoint options']/parent::*</value>
      <webElementGuid>9b8a55d2-f2bf-455c-bbec-87fd86ca66fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
      <webElementGuid>85ff97c6-17a9-4181-8e4a-9dbc00501273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Include endpoint options' or . = 'Include endpoint options')]</value>
      <webElementGuid>84cda90b-19b1-474f-89b7-599b0ac6ba95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
