<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email-confirm-input</name>
   <tag></tag>
   <elementGuidId>de102ca7-07d3-4971-b776-1b8fc26820bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-confirm-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-confirm-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;lieucao16122003@gmail.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c1a7b1f-cc89-4de7-a3ed-b86304ba5212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-10 w-full rounded-lg border border-border-light bg-transparent px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>2b627513-93e4-47db-956d-9a9c85b72f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-confirm-input</value>
      <webElementGuid>0499664c-8bf1-4506-b5d5-325f4044ce59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>lieucao16122003@gmail.com</value>
      <webElementGuid>e6b8923e-527d-4bc9-80d6-c8f6a36804d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-confirm-input&quot;)</value>
      <webElementGuid>4b47e079-4cf0-4a26-89b8-cbd7b783cb0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-confirm-input']</value>
      <webElementGuid>b58a0457-cb8b-45dc-8d20-78e07e972c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rrn:']/div[3]/div/div/input</value>
      <webElementGuid>92b4317e-2042-4b6e-bfd2-6ed73fb0020b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>54e8ee98-0dbe-48dd-a7da-f27da3933276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-confirm-input' and @placeholder = 'lieucao16122003@gmail.com']</value>
      <webElementGuid>180e02ce-8ae1-4857-9100-5ce63ce9f66e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
