<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Not Supported</name>
   <tag></tag>
   <elementGuidId>87520ee7-44d6-494d-bf61-02710d65e226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='includeOptions-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#includeOptions-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Not Supported&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d5c30f80-80cd-4581-8021-8e89cb740292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>includeOptions-label</value>
      <webElementGuid>aef77ef8-ad04-4e78-8212-dba7ba1bb9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>includeOptions</value>
      <webElementGuid>6d591828-4d3e-4b85-8353-49ee1e76bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70</value>
      <webElementGuid>d0be33e6-6336-4f9e-8bea-37c9dd67033d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Supported</value>
      <webElementGuid>9392fa39-7a83-4b34-8317-bc8e68dd1c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;includeOptions-label&quot;)</value>
      <webElementGuid>333ee59a-3855-4284-b3c3-07c78edb2fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='includeOptions-label']</value>
      <webElementGuid>3ae9577b-34ce-46ad-a42d-b55107ee6cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r15:']/div[2]/div/div[2]/div/div/div/label</value>
      <webElementGuid>e127876a-6e34-4cd2-8b37-0afb8717b32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include endpoint options'])[1]/following::label[1]</value>
      <webElementGuid>c6f74b84-55a8-4c6b-b362-7ce15ea91560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='csv (.csv)'])[2]/following::label[2]</value>
      <webElementGuid>f7730629-ef0d-41bc-9ae1-84213c14bb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export all message branches'])[1]/preceding::label[1]</value>
      <webElementGuid>77455c61-deb3-4ac3-be20-540fb83cad3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export all message branches'])[2]/preceding::label[2]</value>
      <webElementGuid>25d1b022-3656-4a3c-bcef-94450131d9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Not Supported']/parent::*</value>
      <webElementGuid>691edf5e-a3c5-4743-8830-59a36da0491a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/label</value>
      <webElementGuid>c421ba45-145a-40c3-a3c0-d54757bc117e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'includeOptions-label' and (text() = 'Not Supported' or . = 'Not Supported')]</value>
      <webElementGuid>e6c3afad-4b59-46b4-8313-df2d37e5ba39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
