<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Max Agent Steps_recursion_limit-input</name>
   <tag></tag>
   <elementGuidId>6774a1d4-2c8e-41b6-a526-67b1a3baabaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recursion_limit-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recursion_limit-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;System&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>180e6fe0-048e-4160-a863-fb81494865eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-lg border border-border-light text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 flex h-10 max-h-10 resize-none border-none bg-surface-secondary px-3 py-2 w-full</value>
      <webElementGuid>4852302a-10f0-483b-adcf-388698c21442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recursion_limit-input</value>
      <webElementGuid>0ece6edc-c8d0-4e97-be46-dc045f4144b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>System</value>
      <webElementGuid>4a2de6eb-707c-4f9a-b7e3-56d97cc7bf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recursion_limit-input&quot;)</value>
      <webElementGuid>1ed9f788-92c6-4ba2-8caf-14621f9a1eb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recursion_limit-input']</value>
      <webElementGuid>73e7d2a4-85d3-4bf9-b3d2-0f1e2fcf7421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>cdf49e3e-6d7d-4fd1-b685-be54124fd758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cc7c0419-97f4-4201-b29d-f14183b4d21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'recursion_limit-input' and @placeholder = 'System']</value>
      <webElementGuid>c9cf8427-01bd-42b0-8d06-1f124949848d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
