<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popover_Love-this</name>
   <tag></tag>
   <elementGuidId>322e9257-3dfe-43d7-bd95-9dff7578145c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='dialog' and contains(@class, 'popover-animate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1977ac6f-74ab-46b1-a5fb-edf0783a3810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2o:</value>
      <webElementGuid>a2ab5834-bdbe-4220-a820-8e261a5cd886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22b50a24-938e-459d-93a6-e2bc306ee91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8b801b86-2651-4563-b9a6-7f75f2e5c430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9d8a8a83-247f-42f1-a72f-9a087e7c5685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-animate flex w-auto flex-col gap-1.5 overflow-hidden rounded-2xl border border-border-medium bg-surface-secondary p-1.5 shadow-lg</value>
      <webElementGuid>7153580d-225f-4aac-a310-c23dbbf69da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b42a01d-732f-45fa-8a3d-d6f0b23e147c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accurate and ReliableCreative SolutionClear and Well-WrittenAttention to Detail</value>
      <webElementGuid>45275d04-a969-442d-bd37-888f458bfdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2o:&quot;)</value>
      <webElementGuid>cae41c2e-318a-4df4-b8c4-0e7410be2f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r2o:']</value>
      <webElementGuid>2231e1c5-6998-4fc8-81cb-ea90e1dada19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal/:r2o:']/div/div</value>
      <webElementGuid>b705bcdf-dcbe-4576-aef1-8899ac5337c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>3e06fa0d-0c2c-4a3d-a1b0-a3e9da6f94d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>05816b9a-e55d-478b-8d75-7389f74232ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r2o:' and (text() = 'Accurate and ReliableCreative SolutionClear and Well-WrittenAttention to Detail' or . = 'Accurate and ReliableCreative SolutionClear and Well-WrittenAttention to Detail')]</value>
      <webElementGuid>bb3fc906-025d-43d7-8741-abed9db4c04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
