<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Image Detail</name>
   <tag></tag>
   <elementGuidId>c76af1e7-6316-43b4-9fe8-2f787b25d6d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imageDetail-dynamic-setting-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='imageDetail-dynamic-setting-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Image Detail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cc45c1a-2de4-44d6-9536-0bb1974256e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex ring-offset-background focus-visible:outline-none rounded-md focus:border-gray-400 focus:bg-gray-50 bg-transparent outline-none focus-within:placeholder:text-text-primary focus:placeholder:text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-gray-400 focus:ring-opacity-20 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-gray-700 dark:border-gray-600 dark:focus:border-gray-600 dark:text-gray-50 dark:shadow-[0_0_15px_rgba(0,0,0,0.10)] dark:focus:outline-none p-0 shadow-none pr-1 border-transparent hover:bg-gray-800/10 dark:hover:bg-white/10 dark:focus:bg-white/10 transition-colors reset-rc-number-input h-auto w-14 border-0 py-1 pl-1 text-center text-xs group-hover/temp:border-gray-200</value>
      <webElementGuid>e5359e20-82be-47a7-af25-054c08995adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imageDetail-dynamic-setting-input</value>
      <webElementGuid>afd789ed-b86e-4699-821c-1bca6236b11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Image Detail</value>
      <webElementGuid>264e94e3-e22e-494e-b580-09177e443b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>83ffb080-61d5-4896-8b9e-05017531046b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imageDetail-dynamic-setting-input&quot;)</value>
      <webElementGuid>8ee6f8da-00fc-47c1-80a8-85189d389b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='imageDetail-dynamic-setting-input']</value>
      <webElementGuid>824bdfaa-f294-417e-b7d0-75f2b3cd15c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[11]/a/div/input</value>
      <webElementGuid>19d40dc3-c278-44cd-bc7f-35f94200f5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/input</value>
      <webElementGuid>57558b77-03d5-45a5-83e4-2e2135d49f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'imageDetail-dynamic-setting-input']</value>
      <webElementGuid>5f6feced-1b6d-4daa-96be-b9557be497ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
