<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reasoning Effort</name>
   <tag></tag>
   <elementGuidId>3979b24e-43ff-4d78-bbd4-e965d0e60ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasoning_effort-dynamic-setting-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reasoning_effort-dynamic-setting-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Reasoning Effort&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4522aa42-39ef-4bef-871a-842c10025819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex ring-offset-background focus-visible:outline-none rounded-md focus:border-gray-400 focus:bg-gray-50 bg-transparent outline-none focus-within:placeholder:text-text-primary focus:placeholder:text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-gray-400 focus:ring-opacity-20 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-gray-700 dark:border-gray-600 dark:focus:border-gray-600 dark:text-gray-50 dark:shadow-[0_0_15px_rgba(0,0,0,0.10)] dark:focus:outline-none p-0 shadow-none pr-1 border-transparent hover:bg-gray-800/10 dark:hover:bg-white/10 dark:focus:bg-white/10 transition-colors reset-rc-number-input h-auto w-14 border-0 py-1 pl-1 text-center text-xs group-hover/temp:border-gray-200</value>
      <webElementGuid>b7f2cbd2-a66a-439e-a9e0-303c9b323fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasoning_effort-dynamic-setting-input</value>
      <webElementGuid>a81b3fa1-416e-4628-8d45-32b5029ab926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Reasoning Effort</value>
      <webElementGuid>379d3d8c-1a3b-4d04-8f07-bc86c1ddc85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Auto</value>
      <webElementGuid>08ca0176-c2f9-4535-a3d0-1b048b713f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasoning_effort-dynamic-setting-input&quot;)</value>
      <webElementGuid>f20c8b83-f49d-4a1d-9fab-4911b8925167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reasoning_effort-dynamic-setting-input']</value>
      <webElementGuid>c0b516cc-fb2c-4127-84d0-fd859d5cf0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[13]/a/div/input</value>
      <webElementGuid>c8c75844-ee61-4bfc-b27e-38668f5d094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/a/div/input</value>
      <webElementGuid>69a3b2da-65b7-49f6-b83e-68778239d0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reasoning_effort-dynamic-setting-input']</value>
      <webElementGuid>2b68b3f6-1c85-408c-a37f-383658c33200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
