<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Max Context Tokens</name>
   <tag></tag>
   <elementGuidId>3271e2d3-fb48-4c7c-91ae-fc6efbcf70c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maxContextTokens-dynamic-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxContextTokens-dynamic-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Max Context Tokens&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dedc8688-9139-4a87-82b3-8d83750e3700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 flex h-9 max-h-9 w-full resize-none rounded-lg border border-border-light bg-surface-secondary px-3 py-2</value>
      <webElementGuid>8222ec52-009d-4be5-b3de-43527356d4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxContextTokens-dynamic-input</value>
      <webElementGuid>f5123119-26c2-4236-a448-8493b84d6dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>System</value>
      <webElementGuid>dd84c3b4-973e-4ce9-9b0f-803175edecad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxContextTokens-dynamic-input&quot;)</value>
      <webElementGuid>7692824f-6d56-4f8f-9ca7-3e2022081558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxContextTokens-dynamic-input']</value>
      <webElementGuid>1cf5a8a8-fb58-4bdb-a2a6-f9aeae558c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/aside/div/nav/div/div/div/div[3]/a/input</value>
      <webElementGuid>b7520bde-1ddb-4cc7-bb15-88fc1ef0095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/input</value>
      <webElementGuid>6468bf84-8d6b-4f35-9a1b-e86e9d80a2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxContextTokens-dynamic-input' and @placeholder = 'System']</value>
      <webElementGuid>1eb279da-586c-4032-80c6-aa67bae81499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
