<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Frequency Penalty</name>
   <tag></tag>
   <elementGuidId>99fb0282-ae0b-435f-8ef4-2d51c8758696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frequency_penalty-dynamic-setting-input-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frequency_penalty-dynamic-setting-input-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton[name=&quot;Frequency Penalty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26974b55-f0cc-4f43-9e4b-db922a6bafa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b6bf3661-1c7a-4eb2-8f03-f8b6b470d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>6d8e9456-8c39-40b3-9731-9e265f195671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>-2</value>
      <webElementGuid>c04b1029-e6fc-4335-97bc-1f3bce249ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a62cb90b-51c3-4e71-9c5f-efd20939c037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a66c5a27-2f24-4942-a686-d4be667e0a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>645e6e4b-5b6e-4900-aa3e-448736354bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frequency_penalty-dynamic-setting-input-number</value>
      <webElementGuid>6591dd5a-4f07-41fd-a4e0-a5d26ca1b4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Frequency Penalty</value>
      <webElementGuid>07ebf32e-a651-4869-b7c3-1cda5d5748d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-input-number-input</value>
      <webElementGuid>121e857b-c8fd-4bc2-8516-b82e02bc0c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>1b9d28d3-4c4a-4678-9443-1b2159f27210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frequency_penalty-dynamic-setting-input-number&quot;)</value>
      <webElementGuid>9fb893de-639a-4d59-bb34-e8415fb7e65a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frequency_penalty-dynamic-setting-input-number']</value>
      <webElementGuid>bb009961-5ea0-476f-a614-35ff4b2ceb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[7]/a/div/div/div/input</value>
      <webElementGuid>4efdb2f9-a37c-4934-9d23-fa7ae40f29c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/div/div/div/input</value>
      <webElementGuid>220e49fc-9681-45e2-a29a-1eb0f8982d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frequency_penalty-dynamic-setting-input-number']</value>
      <webElementGuid>9a5cfeb4-f3df-450c-b709-fce9c1d6a519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
