<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File Token Limit</name>
   <tag></tag>
   <elementGuidId>034e6235-acd9-4c2d-abae-a4ca9a6631e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fileTokenLimit-dynamic-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileTokenLimit-dynamic-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;File Token Limit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d1db190-f108-4ef8-891d-349c28b17806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 flex h-9 max-h-9 w-full resize-none rounded-lg border border-border-light bg-surface-secondary px-3 py-2</value>
      <webElementGuid>e7792534-9235-4bdd-a20e-4461943c1560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileTokenLimit-dynamic-input</value>
      <webElementGuid>7708533a-b2d2-4910-afb9-e1cf45ca2958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>System</value>
      <webElementGuid>d188677f-a596-4b65-9ca3-9bf135dec8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileTokenLimit-dynamic-input&quot;)</value>
      <webElementGuid>fe3187d1-8625-4ca9-81f3-6fdc316c278b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileTokenLimit-dynamic-input']</value>
      <webElementGuid>141162df-5ee7-4bc7-9f3a-ed44851fcb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[18]/a/input</value>
      <webElementGuid>a5045d54-4256-4f8b-8cd8-85c93b9510af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/a/input</value>
      <webElementGuid>1dc5cddd-7e6c-42e6-aa93-f598ccf9b4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fileTokenLimit-dynamic-input' and @placeholder = 'System']</value>
      <webElementGuid>1111dd10-0657-4d66-9799-6a4dbd05def9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
