<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Presence Penalty</name>
   <tag></tag>
   <elementGuidId>ff6c4455-cd29-413b-98f8-4219221b7a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#presence_penalty-dynamic-setting-input-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='presence_penalty-dynamic-setting-input-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton[name=&quot;Presence Penalty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92621b00-852e-4759-b77f-35361cb560d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7bf31bb5-8e13-4785-a228-eeeb6ec96344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>59865d0a-adb9-4ca8-8a22-fe5393a52185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>-2</value>
      <webElementGuid>a4441422-c0ef-46b8-88c6-5a09ff7fc631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>58daad6d-e1f5-4e64-9d50-31a5a7be7419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e04f8c82-8346-4754-919d-72cc71f3af20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>5fa23520-37de-40c3-b66c-c7b41c696a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>presence_penalty-dynamic-setting-input-number</value>
      <webElementGuid>930e6007-4c75-4b06-b0d2-b33f918a4081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Presence Penalty</value>
      <webElementGuid>7084198c-3ab5-4cae-87b1-cd5ff4ed2ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-input-number-input</value>
      <webElementGuid>9f90b8ca-ce32-41d2-99c5-2457b366e127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>583e3c3b-7a62-46a4-bc50-3c66590bd269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;presence_penalty-dynamic-setting-input-number&quot;)</value>
      <webElementGuid>9d19823b-5525-4ce1-8195-a987b7bad5a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='presence_penalty-dynamic-setting-input-number']</value>
      <webElementGuid>61150c46-530c-4e00-b758-49f33e02d694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[8]/a/div/div/div/input</value>
      <webElementGuid>e713369b-3172-4282-9367-9b4ef7a8618f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/div/div/div/input</value>
      <webElementGuid>bd31aea2-aec9-4b99-814c-92d14048506e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'presence_penalty-dynamic-setting-input-number']</value>
      <webElementGuid>c53eb07f-6c9b-4cdd-8f21-640119fcb9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
