<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verbosity</name>
   <tag></tag>
   <elementGuidId>d5c565b6-14cf-43ff-aadd-976f0cf8a16a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verbosity-dynamic-setting-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verbosity-dynamic-setting-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Verbosity&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5b39497-a72a-4b96-a238-f4efd53776ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex ring-offset-background focus-visible:outline-none rounded-md focus:border-gray-400 focus:bg-gray-50 bg-transparent outline-none focus-within:placeholder:text-text-primary focus:placeholder:text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-gray-400 focus:ring-opacity-20 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-gray-700 dark:border-gray-600 dark:focus:border-gray-600 dark:text-gray-50 dark:shadow-[0_0_15px_rgba(0,0,0,0.10)] dark:focus:outline-none p-0 shadow-none pr-1 border-transparent hover:bg-gray-800/10 dark:hover:bg-white/10 dark:focus:bg-white/10 transition-colors reset-rc-number-input h-auto w-14 border-0 py-1 pl-1 text-center text-xs group-hover/temp:border-gray-200</value>
      <webElementGuid>d768e290-a011-400d-b216-00e568c19a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verbosity-dynamic-setting-input</value>
      <webElementGuid>3aa647b0-6903-406e-a739-fc7c82cbae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Verbosity</value>
      <webElementGuid>357e07d1-45ef-443b-95dd-c61f9c9f39a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>None</value>
      <webElementGuid>c9e48822-4947-4d21-94c7-92fb93e0a7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verbosity-dynamic-setting-input&quot;)</value>
      <webElementGuid>84f33f08-5e0d-4d71-b9ad-3c4b700b5394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verbosity-dynamic-setting-input']</value>
      <webElementGuid>0184d578-d86b-4b91-9b10-3d33b9fbbfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[16]/a/div/input</value>
      <webElementGuid>a6c36246-267f-4b15-9a76-9c02478c22b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/a/div/input</value>
      <webElementGuid>1a803c8a-d7a5-47f0-97f4-2919ea5b633e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verbosity-dynamic-setting-input']</value>
      <webElementGuid>1da50a98-1f54-4db3-8c1d-c971874fd267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
