<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Max Output Tokens</name>
   <tag></tag>
   <elementGuidId>7103ec5d-49f9-4246-8a81-68e14afb2e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#max_tokens-dynamic-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='max_tokens-dynamic-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Max Output Tokens&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df8ecac5-d981-4a4f-8b7c-b563c1131d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 flex h-9 max-h-9 w-full resize-none rounded-lg border border-border-light bg-surface-secondary px-3 py-2</value>
      <webElementGuid>fa304cbf-1beb-4d2b-b129-dfaa57f4f87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>max_tokens-dynamic-input</value>
      <webElementGuid>cd9195f6-9a63-48d9-a729-7c23fbfab9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>System</value>
      <webElementGuid>1300cfb1-3579-437c-9f40-afad38ffd720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;max_tokens-dynamic-input&quot;)</value>
      <webElementGuid>7bd29742-af2d-47e7-8f6d-3bcb03d373b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='max_tokens-dynamic-input']</value>
      <webElementGuid>1ccb3020-8229-47a0-8ae9-a3111938324a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/aside/div/nav/div/div/div/div[4]/a/input</value>
      <webElementGuid>f7073a91-bc56-47f9-b37e-dfe6b88fae99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/input</value>
      <webElementGuid>8097f151-1b42-439f-8695-b2862ef79b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'max_tokens-dynamic-input' and @placeholder = 'System']</value>
      <webElementGuid>9c81a94f-d0af-4f50-9b62-2fc225c22da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
