<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Temperature</name>
   <tag></tag>
   <elementGuidId>54bdd8d1-006d-488b-9579-80258f2c6bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#temperature-dynamic-setting-input-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='temperature-dynamic-setting-input-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton[name=&quot;Temperature&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0acd5b10-c080-42e0-b792-d1156455ca0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a69d255-67aa-4dad-918e-7c96a96cdc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>46a6d8df-0920-4222-9f69-d46338b3b758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0da17208-cb81-4b24-859b-05ae0d669b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>98477a04-9db1-4afb-83c6-dbe53efdf0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>1.43</value>
      <webElementGuid>9c826046-720f-4298-9d53-cc3afadc1e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>42fbbbc7-bfc8-4da3-9a8d-46e20d4df416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>temperature-dynamic-setting-input-number</value>
      <webElementGuid>7d830a62-ade6-49d6-8e31-43e4c393fe9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Temperature</value>
      <webElementGuid>ab2c7feb-59a4-4940-8785-36c204e5eb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-input-number-input</value>
      <webElementGuid>ac962962-a494-46e8-8a5f-25dfb20f512c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1.43</value>
      <webElementGuid>fb430c55-2f3f-4fc2-957c-345b707cad25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperature-dynamic-setting-input-number&quot;)</value>
      <webElementGuid>0674363a-b77c-4000-8263-3182ac34b043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='temperature-dynamic-setting-input-number']</value>
      <webElementGuid>94c5a8e3-346a-4bbe-ae58-1f475844a7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div[5]/a/div/div/div/input</value>
      <webElementGuid>3ae6e876-30aa-4b28-948b-dbf42b0edf7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4bb5de5d-a6c4-48da-9908-c4d857c2da0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'temperature-dynamic-setting-input-number']</value>
      <webElementGuid>aed3e841-f186-4dda-8f71-26d4e4d8bc15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
