<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Custom</name>
   <tag></tag>
   <elementGuidId>7f54bb8a-9b05-4395-a4c2-c93370c19934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promptPrefix-dynamic-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='promptPrefix-dynamic-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Custom Instructions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9a1da774-e67c-4ee5-b134-5aabbbc6ef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>7dfd414c-7f4d-4d06-a32d-6739e5f8f079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promptPrefix-dynamic-textarea</value>
      <webElementGuid>43c93c7c-8b5e-460a-ae05-b213f9b5c02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Custom Instructions</value>
      <webElementGuid>82e9b409-5789-4f29-baf6-6b522271290c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Set custom instructions to include in System Message. Default: none</value>
      <webElementGuid>6dbedf37-586b-4f16-9517-f0e0a06578c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex max-h-[138px] min-h-[100px] w-full resize-none rounded-lg border border-border-light bg-surface-secondary px-3 py-2 text-sm focus:outline-none</value>
      <webElementGuid>349c1d4d-4976-40bc-a51a-45ea444dcb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promptPrefix-dynamic-textarea&quot;)</value>
      <webElementGuid>2a4fe7d0-d22b-4bf7-8e87-727d55443ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='promptPrefix-dynamic-textarea']</value>
      <webElementGuid>0d7951e1-4609-443e-a324-7bde8d6db183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/aside/div/nav/div/div/div/div[2]/a/textarea</value>
      <webElementGuid>341acae3-86ed-4889-a2ad-29ba7fa3dbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0bc7ae49-1351-4660-845e-511ecd1bcecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'promptPrefix-dynamic-textarea' and @placeholder = 'Set custom instructions to include in System Message. Default: none']</value>
      <webElementGuid>824313d7-30b3-4e57-af1b-f229f6bde3e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
