<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add prompt</name>
   <tag></tag>
   <elementGuidId>5564e61e-8fae-41a0-ba94-77c81347c6f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7654b8f8-57b5-4e72-b375-a898cbf1a040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eaddf86d-5618-4ffe-93eb-a8b425e85594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-surface-submit hover:bg-surface-submit-hover h-9 rounded-lg px-3 gap-1.5 text-white</value>
      <webElementGuid>e5cd39bf-5c8c-416a-94f8-1343d59d0e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add prompt</value>
      <webElementGuid>c31af1cb-e470-46c3-9dec-34a18157cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add prompt</value>
      <webElementGuid>58a9ea06-8b3f-457c-9622-729cedee14ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:rl:-content-shared&quot;)/div[@class=&quot;flex flex-col gap-6&quot;]/section[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/button[@class=&quot;inline-flex items-center justify-center whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-surface-submit hover:bg-surface-submit-hover h-9 rounded-lg px-3 gap-1.5 text-white&quot;]</value>
      <webElementGuid>f95f432d-a503-4f25-8a85-6464f4939a9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>7636b47f-d9d2-4c97-bc3a-779b4378168f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:rl:-content-shared']/div/section[2]/div/button</value>
      <webElementGuid>1750141f-0d1a-40e0-9f40-a8584ec8b7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prompts'])[1]/following::button[1]</value>
      <webElementGuid>87804b83-2b11-4269-b0c9-815d45e75459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add agent'])[1]/following::button[1]</value>
      <webElementGuid>b8ae894b-4d8e-4a86-bb20-2af56449a8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lieucao16122003@gmail.com'])[1]/preceding::button[1]</value>
      <webElementGuid>db58000f-4a5b-41b2-905f-91dddda740df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Files'])[1]/preceding::button[1]</value>
      <webElementGuid>b5ca54e4-7dd7-4961-bec7-57c8f1eab592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add prompt']/parent::*</value>
      <webElementGuid>09628346-cca5-47cc-9de3-a45669e0f12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button</value>
      <webElementGuid>cdbab37b-b032-41a9-b1f7-8f00137332fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add prompt' or . = 'Add prompt')]</value>
      <webElementGuid>1e1cc26b-e838-4664-87c1-dec331cba8e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
