<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Response_text</name>
   <tag></tag>
   <elementGuidId>ca0fb405-9fc0-40b9-8b91-f86e22428195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'text' and @data-testid = 'message-text-editor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;message-text-editor&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ce0b45eb-3b5f-41fa-b554-0120b54d8860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>34885e31-04ee-4a37-a38b-30bba39f8406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5609295-22f1-4fec-98f1-a3c74ac40749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>message-text-editor</value>
      <webElementGuid>36565fd2-eba0-444c-bb04-60063294bfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>markdown prose dark:prose-invert light whitespace-pre-wrap break-words pl-3 md:pl-4 m-0 w-full resize-none border-0 bg-transparent py-[10px] placeholder-text-secondary focus-visible:ring-0 md:py-3.5 text-left max-h-[65vh] pr-3 md:max-h-[75vh] md:pr-4 focus:outline-none focus:ring-0 focus:ring-opacity-0 focus:ring-offset-0</value>
      <webElementGuid>d1a820cb-2382-4cce-984c-29f7685813a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Editable Message</value>
      <webElementGuid>252e8b6e-60f0-4753-b104-9eb96773c4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2e479cb3-a4a4-4529-b4d6-414a6cda012b&quot;)/div[@class=&quot;relative flex flex-col w-11/12 agent-turn&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/div[@class=&quot;flex min-h-[20px] max-w-full flex-grow flex-col gap-0&quot;]/div[@class=&quot;text-message flex min-h-[20px] flex-col items-start gap-3 overflow-visible [.text-message+&amp;]:mt-5&quot;]/div[@class=&quot;bg-token-main-surface-primary relative flex w-full flex-grow flex-col overflow-hidden rounded-2xl border border-border-medium text-text-primary [&amp;:has(textarea:focus)]:border-border-heavy [&amp;:has(textarea:focus)]:shadow-[0_2px_6px_rgba(0,0,0,.05)]&quot;]/textarea[@class=&quot;markdown prose dark:prose-invert light whitespace-pre-wrap break-words pl-3 md:pl-4 m-0 w-full resize-none border-0 bg-transparent py-[10px] placeholder-text-secondary focus-visible:ring-0 md:py-3.5 text-left max-h-[65vh] pr-3 md:max-h-[75vh] md:pr-4 focus:outline-none focus:ring-0 focus:ring-opacity-0 focus:ring-offset-0&quot;]</value>
      <webElementGuid>ed8beea5-a228-4749-8481-df3652201f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='text']</value>
      <webElementGuid>7fcf3e17-848c-4a1a-8ffc-14d0ef6fa817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2e479cb3-a4a4-4529-b4d6-414a6cda012b']/div[2]/div/div/div/div[2]/textarea</value>
      <webElementGuid>47f00556-1606-4499-971b-55790da3abe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>73fff436-62c3-4f23-9e16-ab27c088a110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'text']</value>
      <webElementGuid>3ce3f125-cd7f-4038-bad2-fa7ef354fc08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
