<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filename_filename</name>
   <tag></tag>
   <elementGuidId>dd9bb5b8-f041-408c-9711-6dc0304d47c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Set the filename&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62540009-f8b9-4b63-8041-98957dc11e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-10 w-full rounded-lg border border-border-light bg-transparent px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50</value>
      <webElementGuid>c2ed6845-adb8-40fa-ab5d-8df608dab92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filename</value>
      <webElementGuid>887b5bd4-be55-4207-9cbe-f12961dadfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Set the filename</value>
      <webElementGuid>9fa04157-c5c4-45f9-aaeb-f0e90e7b6d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Core Chat Test Responses</value>
      <webElementGuid>d767b465-9a38-4e38-9b7d-9947a7c74f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filename&quot;)</value>
      <webElementGuid>ce5e509d-539d-4cef-9a6e-e87944a7fb10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filename']</value>
      <webElementGuid>0e89198e-1fd7-4e47-8e81-8c7b0ecde33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r59:']/div[2]/div/div/div/input</value>
      <webElementGuid>132569a9-c992-46a4-9694-fba6da3b5091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>8f86fc81-9e4c-40bc-a1a2-27efc0468ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filename' and @placeholder = 'Set the filename']</value>
      <webElementGuid>1b81ab1d-1885-4cf0-9d79-3e5184cbb4c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
