<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popover_Needs improvement</name>
   <tag></tag>
   <elementGuidId>18f24075-e974-4320-9710-623751b7b3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'popover-animate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47958cb1-6a08-45be-a1b9-e26b0d367b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2s:</value>
      <webElementGuid>08a1969f-b760-4887-86f1-754a316388eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f10a63bd-4d35-4cd2-a72c-2dad45400f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>6e434b1a-d273-4ca0-8fe9-e48570af6bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>eed6dda1-a1c2-4386-aab9-f479a902e241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-animate flex w-auto flex-col gap-1.5 overflow-hidden rounded-2xl border border-border-medium bg-surface-secondary p-1.5 shadow-lg</value>
      <webElementGuid>e2255573-dcd7-4769-8cb9-067dc7ec1b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb081d89-3841-41f2-9190-5411a2de33ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Didn't match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue</value>
      <webElementGuid>e48e5151-e52b-4a22-bf59-af1611af9be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2s:&quot;)</value>
      <webElementGuid>ddd20b02-15ce-42ef-b9de-7a84c4b4a433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r2s:']</value>
      <webElementGuid>d2acb1e1-e446-421a-bffa-cc5b7502a091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal/:r2s:']/div/div</value>
      <webElementGuid>1b1dcf5f-9ebe-4107-9293-3d81ddccc2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[3]</value>
      <webElementGuid>77be1797-4cf9-4a44-9003-ca0bd12b4cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[5]</value>
      <webElementGuid>2c281cfc-97cc-4862-ba63-a606eed64062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>05668211-c5b5-495b-96c5-9197e6b5eebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r2s:' and (text() = concat(&quot;Didn&quot; , &quot;'&quot; , &quot;t match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue&quot;) or . = concat(&quot;Didn&quot; , &quot;'&quot; , &quot;t match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue&quot;))]</value>
      <webElementGuid>a4f95eab-1fe0-4433-8e76-b9975ec09e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
