<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popover_Needs improvement</name>
   <tag></tag>
   <elementGuidId>ca1ee4c6-5bf8-4b7e-9b54-1d7693ba6c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='dialog' and contains(@class, 'popover-animate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9181b000-a5c4-47af-b4b9-2fe54de38977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2i:</value>
      <webElementGuid>b5bda1d4-80e1-49af-89d3-1200dc0662eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>43ce2fa8-4a8c-45bd-bb4e-05ebb2d3c255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>7e012530-53a4-4210-94eb-f8f3c7ee568c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>64879381-d6f2-4bc0-982e-ace12a61c4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-animate flex w-auto flex-col gap-1.5 overflow-hidden rounded-2xl border border-border-medium bg-surface-secondary p-1.5 shadow-lg</value>
      <webElementGuid>67f8a6c8-149c-4da4-9cc2-d75cde536e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>456879e1-13ad-4f4a-9673-dccd5443a789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Didn't match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue</value>
      <webElementGuid>2f906b55-7eda-4603-9859-cd56c131752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2i:&quot;)</value>
      <webElementGuid>a0ba789e-fc50-42ae-9746-c7e13d995521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r2i:']</value>
      <webElementGuid>bd79a5e6-5114-499d-88aa-6961c67f7cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal/:r2i:']/div/div</value>
      <webElementGuid>97d8cebf-40bd-41ee-8a99-cb2d6d1dae77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[3]</value>
      <webElementGuid>8e6a3d47-9ae8-44e2-b12b-16100a10e90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>70252f5c-3496-4444-bade-d0801d808f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r2i:' and (text() = concat(&quot;Didn&quot; , &quot;'&quot; , &quot;t match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue&quot;) or . = concat(&quot;Didn&quot; , &quot;'&quot; , &quot;t match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue&quot;))]</value>
      <webElementGuid>1d0d7c8f-0e30-4af4-821b-5caaa882d06e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
