<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popover_Needs improvement</name>
   <tag></tag>
   <elementGuidId>18f24075-e974-4320-9710-623751b7b3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = ':r2s:']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'popover-animate')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f884dcf-1391-4d58-a698-4251820eb949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2s:</value>
      <webElementGuid>ff1b2fec-bb02-435e-9e4e-34758f70de50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b3a01cbd-8bc7-4743-a9a1-bae43788cdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>a9782dda-4204-48a9-83f3-e02a64c965aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a440f799-1d00-4e57-a6fb-195cdc7cfe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-animate flex w-auto flex-col gap-1.5 overflow-hidden rounded-2xl border border-border-medium bg-surface-secondary p-1.5 shadow-lg</value>
      <webElementGuid>42103a0e-5f9b-4300-90dd-13c1ec16c249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dae23e8f-bbcf-406f-8470-25c4f5701183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Didn't match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue</value>
      <webElementGuid>4158eb49-49d2-47de-9920-a7edea2f1215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r2s:&quot;)</value>
      <webElementGuid>91a8aebc-2be9-498a-9a06-c7988f6be688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r2s:']</value>
      <webElementGuid>706216db-d100-4b63-b5ed-2cbd2c3ff10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal/:r2s:']/div/div</value>
      <webElementGuid>767382ca-fe5b-43a7-a0ed-5a11b15d3d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[3]</value>
      <webElementGuid>e9362362-3bcc-46f0-a85a-16512354bdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[5]</value>
      <webElementGuid>ddfb9ed6-c25d-4716-8fec-3616cdf448d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>3269c3d8-a658-4f72-83d1-3bcd9fe8e0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r2s:' and (text() = concat(&quot;Didn&quot; , &quot;'&quot; , &quot;t match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue&quot;) or . = concat(&quot;Didn&quot; , &quot;'&quot; , &quot;t match my requestInaccurate or incorrect answerPoor style or toneExpected an imageRefused without reasonLacked useful informationOther issue&quot;))]</value>
      <webElementGuid>6276c335-9edf-43b9-968f-49011a1b8856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
