<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listbox_Export-type</name>
   <tag></tag>
   <elementGuidId>7a106100-d12c-494b-8c0f-50081022883e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='listbox' and contains(@class, 'popover-ui')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;screenshot (.png)text (.txt)markdown (.md)json (.json)csv (.csv)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f335430-9af9-4a64-8227-ac33f97fae65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r5n:</value>
      <webElementGuid>b7a47fdc-dfe1-4223-9583-889bf10bebfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>e79e9e34-d0bb-440f-a2dd-a9cec0be35b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e8b588b5-5726-436c-a3b6-dbe510c4f8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-ui text-sm z-50 max-h-[80vh] overflow-y-auto [pointer-events:auto]</value>
      <webElementGuid>33eafca1-7170-47cc-a894-bd41508bf667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-open</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cd25314-607b-452c-97a1-3ff5c0e35025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-enter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>075c5fa4-742d-4c3c-b72d-f97ddab44248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>screenshot (.png)text (.txt)markdown (.md)json (.json)csv (.csv)</value>
      <webElementGuid>b0378870-0002-45f9-b527-0f3dd389e18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r5n:&quot;)</value>
      <webElementGuid>8f8f2581-62f3-49b3-bfa2-e8bf97a731d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=':r5n:']</value>
      <webElementGuid>591efc8e-7a1b-409a-b59b-b2d81201bc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r59:']/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>c20c181c-ee63-4abc-b028-ac54cef47ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='screenshot (.png)'])[1]/following::div[2]</value>
      <webElementGuid>8fcd8bd0-1275-473d-aad7-fd848e0907d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::div[4]</value>
      <webElementGuid>66ac4985-9bff-4b11-bb08-dd45c301ca6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>431a97db-c09f-4a79-9792-4a3f0f726d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = ':r5n:' and (text() = 'screenshot (.png)text (.txt)markdown (.md)json (.json)csv (.csv)' or . = 'screenshot (.png)text (.txt)markdown (.md)json (.json)csv (.csv)')]</value>
      <webElementGuid>226e1333-e8e1-4e0e-b607-74e72e422f0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
